---
title: "Maddison 2020 database of GDP"
subtitle: "Plotting examples making use of 'ggpp' and 'ggpmisc'"
author: "Pedro J. Aphalo"
date: 2023-03-04
---

# Under construction!!

```{r, message=FALSE}
library(ggpmisc)
library(ggrepel)
library(readxl)
library(tidyr)
library(dplyr)
```

The database is available on-line at the [Maddison project page](https://www.rug.nl/ggdc/historicaldevelopment/maddison/releases/maddison-project-database-2020?lang=en).
I will use a locally cached copy of the file, the code below downloads the file
only if the local copy does not already exist.

```{r, message=FALSE, }
if (!file.exists("mpd2020.xlsx")) {
  download.file("https://www.rug.nl/ggdc/historicaldevelopment/maddison/data/mpd2020.xlsx",
                destfile = "mpd2020.xlsx",
                mode = "wb")
}

# full data in long form
maddison2020_Full.df <- read_xlsx("mpd2020.xlsx", sheet = "Full data")
colnames(maddison2020_Full.df)
nrow(maddison2020_Full.df)
unique(maddison2020_Full.df$countrycode)

# regional data in wide form
header.df <- read_xlsx("mpd2020.xlsx", sheet = "Regional data", n_max = 3)
data.df <- read_xlsx("mpd2020.xlsx", sheet = "Regional data", skip = 2)
colnames(data.df) <- c("Year", as.character(header.df[1, ])[-1])
# ncol(data.df)

# regional data in long form
GDPpc.df <- 
  pivot_longer(data.df[c(1:9, 19)], 
               values_to = "GDPpc", 
               names_to = "region",
               cols = colnames(data.df)[c(2:9)])
colnames(GDPpc.df) <- 
  gsub("World GDP pc", "GDPpc_World", colnames(GDPpc.df))


population.df <-
  pivot_longer(data.df[c(1, 10:18)], 
               values_to = "population", 
               names_to = "region",
               cols = colnames(data.df)[10:17])
colnames(population.df) <- 
  gsub("World", "population_World", colnames(population.df))

maddison2020_Regional.df <- full_join(GDPpc.df, population.df)
colnames(maddison2020_Regional.df)
nrow(maddison2020_Regional.df)

maddison2020_World.df <- rename(data.df[ , c("Year", "World", "World GDP pc")],
                                year = Year,
                                pop_World = World,
                                gdp_World = "World GDP pc")

maddison2020_Combined.df <- 
  left_join(maddison2020_Full.df,
            maddison2020_World.df, 
            by = "year", multiple = "first")

# cleanup
rm(header.df, data.df, GDPpc.df, population.df)
```

```{r}
ggplot(maddison2020_Regional.df, 
       aes(Year, GDPpc, colour = region)) +
  geom_line(na.rm = TRUE) +
  scale_x_continuous(limits = c(1900, NA)) +
  scale_y_log10()
```



```{r}
ggplot(subset(maddison2020_Full.df, 
              year >= 1905 & countrycode %in% 
                c("ARG", "CHL", "BOL", "BRA", "URY", "VEN", "COL", "CUB", "MEX", "PER")), 
       aes(year, gdppc, colour = country, label = countrycode)) +
  geom_line(show.legend = FALSE) +
  geom_text_repel(data = function(x) {subset(x, year == 2018)},
             position = position_nudge_to(x = 2025), colour = "black", size = 2.5,
             direction = "y", box.padding = 0.1, min.segment.length = 0) +
  geom_text_repel(data = function(x) {subset(x, year == 1905)},
             position = position_nudge_to(x = 1898), colour = "black", size = 2.5,
             direction = "y", box.padding = 0.1, min.segment.length = 0) +
  scale_y_log10(breaks = c(500, 1000, 2000, 5000, 10000, 20000), limits = c(500, 25000))
```

```{r}
ggplot(subset(maddison2020_Full.df, year >= 2000 & countrycode %in% c("ARG", "CHL", "BOL", "BRA", "URY", "VEN", "COL", "CUB", "NIC", "MEX", "PER")), 
       aes(year, gdppc, colour = country, label = countrycode)) +
  geom_line(show.legend = FALSE) +
  geom_text_repel(data = function(x) {subset(x, year == 2018)},
             position = position_nudge_to(x = 2019), colour = "black", size = 3,
             direction = "y", box.padding = 0.1, min.segment.length = 0) +
  geom_text_repel(data = function(x) {subset(x, year == 2000)},
             position = position_nudge_to(x = 1999), colour = "black", size = 3,
             direction = "y", box.padding = 0.1, min.segment.length = 0) +
  expand_limits(x = c(1998, 2020)) +
  scale_y_log10(breaks = c(2000, 5000, 10000, 20000), limits = c(2000, 25000)) +
  theme_bw()
```

```{r}
ggplot(subset(maddison2020_Combined.df, year >= 1900 & 
                countrycode %in% 
                c("ARG", "CHL", "BOL", "BRA", "URY", "VEN", "COL", "CUB", "NIC", "MEX", "PER")), 
       aes(gdp_World, gdppc, colour = country, label = countrycode)) +
  geom_line(show.legend = FALSE, na.rm = TRUE) +
  geom_abline(linetype = "dotted") +
  scale_y_log10(breaks = c(2000, 5000, 10000, 20000), limits = c(2000, 20000)) +
  scale_x_log10(breaks = c(2000, 5000, 10000, 20000), limits = c(2000, 20000)) +
  facet_wrap(facets = vars(country), ncol = 5) +
  theme_bw()
```


```{r}
ggplot(subset(maddison2020_Combined.df, year >= 1900 & 
                countrycode %in% 
                c("FIN", "SWE", "FRA", "GBR", "POL", "ESP", "ITA", "DEU", "NLD", "PRT")), 
       aes(gdp_World, gdppc, colour = country, label = countrycode)) +
  geom_line(show.legend = FALSE, na.rm = TRUE) +
  geom_abline(linetype = "dotted") +
  scale_y_log10(breaks = c(2000, 5000, 10000, 20000), limits = c(2000, 20000)) +
  scale_x_log10(breaks = c(2000, 5000, 10000, 20000), limits = c(2000, 20000)) +
  facet_wrap(facets = vars(country), ncol = 5) +
  theme_bw()
```



```{r}
ggplot(subset(maddison2020_Combined.df, year >= 1900 & 
                countrycode %in% 
                c("UGA", "GAB", "EGY", "TUN", "KEN", "LBR", "ZAF", "TCD", "SEN", "BWA")), 
       aes(gdp_World, gdppc, colour = country, label = countrycode)) +
  geom_line(show.legend = FALSE, na.rm = TRUE) +
  geom_abline(linetype = "dotted") +
  scale_y_log10(breaks = c(2000, 5000, 10000, 20000), limits = c(1000, 20000)) +
  scale_x_log10(breaks = c(2000, 5000, 10000, 20000), limits = c(1000, 20000)) +
  facet_wrap(facets = vars(country), ncol = 5) +
  theme_bw()
```


```{r}
ggplot(subset(maddison2020_Combined.df, year >= 1900 & 
                countrycode %in% 
                c("RUS", "UKR", "ARM", "AZE", "BLR", "UZB")), 
       aes(gdp_World, gdppc, colour = country, label = countrycode)) +
  geom_line(show.legend = FALSE, na.rm = TRUE) +
  geom_abline(linetype = "dotted") +
  scale_y_log10(breaks = c(2000, 5000, 10000, 20000), limits = c(3000, 20000)) +
  scale_x_log10(breaks = c(2000, 5000, 10000, 20000), limits = c(3000, 20000)) +
  facet_wrap(facets = vars(country), ncol = 5) +
  theme_bw()
```
