---
title: "Multiple comparisons with 'ggpmisc'"
subtitle: "Labelling plots with test results"
author: "Pedro J. Aphalo"
date: 2023-08-06
date-modified: 2023-08-06
keywords: [ggplot2 pkg, ggpp pkg, ggpmisc pkg, data labels, plot annotations, multiple comparisons]
categories: [Plotting examples]
abstract: |
  Example R code for plots with labels reporting the results of multiple comparisons computed with `stat_multcomp()` from R package 'ggpmisc'.
code-fold: true
format:
  html: 
    code-link: true
    code-tools: true
draft: true
---

## Introduction

Package 'ggsignif' seems to be the most popular (only?) implementation of
pairwise comparisons for ggplots. I have used this package and it does a a good
job for automating some simple tests, but it has limitations. Recently I wished
to have more flexible formatting base on _plotmath expressions_ of the labels as
well as the ability to adjust _p_-values, multiple comparison procedures or use
fitted contrasts. Adjusting _p_-values is of crucial importance and in my view
should be the default behaviour. There is an issue at GitHub and questions in
StackOverflow wishing this to be supported.

Package 'ggsignif', although maintained, is no longer under active development.
The authors suggest creating pull requests for new features. I studied the code
and it seems to me that the coupling between the statistic and geometry is
unnecessarily tight and would make it difficult to create a pull request that
would fulfil my needs. In particular, the _manual_ mode feels like an
afterthought modification to the statistic, and does not follow the expectations
of the grammar of graphics that statistics do computations and geometries create
a graphical representation. So, I decided to implement from scratch enhanced
functionality in packages 'ggpp' and 'ggpmisc' similar to that in package
'ggsignif'.

Package 'ggpp' mainly defines geometries and scales that can be useful for the
development of other packages. Package 'ggpmisc' implements mostly statistics
and also imports and re-exports package 'ggpp'. 

## Package 'ggpp' (>= 0.5.4)

I added `geom_text_pairwise()` and `geom_label_pairwise()` to package 'ggpp'. 
Writing the code of `geom_text_pairwise()` and `geom_label_pairwise()` took
only a couple of hours, using the existing code of `geom_text_s()` and
`geom_label_s()` as a base. The user interface is, thus, consistent with that of
other related layer functions in package 'ggpp'. These geometries are fully
functional on their own and by default make use of `ggplot2::stat_identity()`.
Example R code of their use in available in page 
[Pairwise labels with 'ggpp'](https://www.r4photobiology.info/galleries/pairwise-labels.html).

These geometries are convenience layer functions, as the same plots can be
created by adding separately the segment and text or label layers to a plot.

## Package 'ggpmisc' (>= 0.5.4)

I added `stat_multcomp()` to package 'ggpmisc'. This new statistics can use the
new geometries from package `ggpp`. The code of function `stat_multcomp()` makes
use of function `glht()` from R package 'multcomp', which takes as argument a
fitted model object. Thus, `stat_multcomp()` first fits a model to the data,
and if the main effect of _x_ is statistically significant runs multiple
comparison pairwise tests using General Linear Hypothesis approach. Additional
code builds formatted character strings to be used as labels and attempts to set 
good defaults for the labels' positions. Two types of labels are currently
available: labelled "bars" (or segments with attached text or labels) connecting
the compared pair of factor levels, or more traditional letters (generated
using R package 'multcompView'). 

`stat_multcomp()` is still under development. Currently only "Tukey" contrasts 
are supported. The order of letters in letter labels is currently not the best
and will change. It has been tested only with `method = "lm"`, although several
other model fit functions should also work.

## Code examples




