---
title: "photobiologyInOut 0.4.24"
author: "Pedro J. Aphalo"
date: 2022-05-15
categories: [R Package Update]
keywords: [photobiologyInOut pkg]
---

This non-code-breaking update brings a few new features and tracks deprecations in package 'tidyr'.

The main changes from <span style="color: #0000ff;">version</span> <span style="color: #0000ff;">0.4.23 </span>the previous CRAN release, are:
<ul>
 	<li>Replace use of deprecated `tidyr::gather_()`.</li>
 	<li>Add function `read_cid_spectravue_csv()` supporting data import from measurements CSV files output by CID Bio-Science's SpectraVue CI-710s leaf spectrometer.</li>
 	<li>Add function `read_foreign2mspct()` to apply an import function to a list of files.</li>
 	<li>Add color-related functions `spct_CRI()`, `spct_CCT()` and `expect_SSI()` implemented as wrappers to functions in package 'colorSpec'. These functions accept `source_spct` objects as arguments. CRI, CCT and SSI are quantities used to describe light used for illumination, photography, cinematography and video.</li>
 	<li>Documentation web site at <a href="https://docs.r4photobiology.info/photobiologyInOut/">http://docs.r4photobiology.info/photobiologyInOut/</a>.</li>
</ul>
<span style="text-indent: 0em;"><strong><span style="color: #0000ff;">NOTE:</span> This version of the package is on its way to <span style="color: #0000ff;">CRAN</span>.</strong></span>

<span style="text-indent: 0em;">Please raise issues concerning bugs or enhancements to this package through Bitbucket at </span><a style="text-indent: 0em;" href="https://github.com/aphalo/photobiologyinout/issues">https://github.com/aphalo/photobiologyinout/issues</a>
