---
title: "gginnards >= 0.1.1 updates"
subtitle: "gginnards: Explore the Innards of 'ggplot2' Objects"
author: "Pedro J. Aphalo"
date: 2022-10-15
date-modified: 2024-04-07
categories: [R Package Update]
keywords: [gginnards pkg]
---

::: callout-note

Since moving the site to Quarto I am updating this post to give a concise
overview of changes. Differences between versions are listed in detail in the
[NEWS file](https://docs.r4photobiology.info/gginnards/news/).

:::

## Overview of changes

_Version 0.2.0_ brings new geometries `geom_debug_panel()` and `geom_debug_group()` supporting printing of `params` in addition to printing of a `data` summary and updated _known_ aesthetic names.

_Version 0.1.2_ fixes one bug.

_Version 0.1.1_ is a maintenance release, with minor enhancements and edits for compatibility with upcoming 'ggplot2' 3.4.0. The only highly visible change is in more clearly separating the roles of the debug statistics and the debug geom by setting `geom_null()` as the default for the statistics. It also contains bug fixes.

::: callout-note

[*Documentation web site*](http://docs.r4photobiology.info/gginnards/) includes all help pages, with output from all examples, vignettes in HTML format and a cheatsheet as a PDF file.

Please raise issues concerning bugs or enhancements to this package through GitHub at <https://github.com/aphalo/gginnards/issues>. Pull requests are also welcome.

:::
