project:
  type: website

website:
  title: "Using R for Photobiology"
  site-url: https://www.r4photobiology.info/static/
  favicon: r4p-favicon.png
  search: true
  navbar:
    logo: r4p-logo.png
    right:
      - icon: house-door
        text: blog
        href: index.qmd
      - icon: file-richtext
        href: pages.qmd
      - icon: images
        text: gallery
        href: galleries.qmd
      - icon: box-seam
        href: pages/packages-status.qmd
      - icon: info-square
        text: Resources
        menu:
          - icon: question-square
            text: Help
            href: pages/help.qmd
          - icon: sun
            text: Suite _R for Photobiology_
            href: pages/r4p-introduction.qmd
          - icon: book
            text: Book _Learn R - As a Language_
            href: https://www.learnr-book.info/
      - icon: person
        text: About
        menu:
          - icon: pc-display
            text: About _this site_
            href: pages/about.qmd
          - icon: person
            text: About _Pedro J. Aphalo_
            href: pages/pedro.qmd
          - icon: github
            text: GitHub _this site_
            href: https://github.com/aphalo/r4p-blog/
  page-footer:
    right:
      - href: pages/about.qmd
    left:
      - text: "ISSN 2343-3248 (Helsinki, Finland)"
    center:
      - text: ORCID
        href: https://orcid.org/0000-0003-3385-972X
format:
  html:
    theme: sandstone
    css: styles.css

editor: source

# for supported icons see https://icons.getbootstrap.com/
