---
title: "Home page"
subtitle: "A brief presentation of the site"
fig-format: svg
editor:
  markdown: 
    wrap: 72
format:
  html:
    code-fold: false
    code-tools: true
listing:
  - id: recent-posts
    max-items: 3
    contents: 
      - posts
    sort: "date-modified desc" 
    type: grid
    image-placeholder: r4p-logo.png
  - id: recent-pages
    max-items: 3
    contents: 
      - pages
    sort: "date desc" 
    type: grid
    image-placeholder: r4p-logo.png
  - id: recent-galleries
    max-items: 3
    contents: 
      - galleries
    sort: "date desc" 
    type: grid
    image-placeholder: r4p-logo.png
  - id: recent-senpep
    max-items: 3
    contents: 
      - senpep-posts
    sort: "date desc" 
    type: grid
    image-placeholder: r4p-logo.png
---

_If you are interested in the R language, data visualization, data analysis, 
the daylight spectrum, measurement of light and optical properties or in how
plants perceive and respond to the characteristics of the light environment
in which they grow, you are likely to find something of interest among the more
than a hundred pages and posts at this site._

I have written the contents of this web site over many years. I continue adding new material but it is also a compilation, with some updates, of what I have written on earlier web sites that do no longer exist or may soon be terminated. Because of this this site is organized in _sections_, each one with its own index page (see contents menu entry). 

**Recently published content is showcased below.**

::: {.callout-note collapse=true}
## R Blog

The [R blog](posts.qmd) contains short articles, mostly news that once
published are not revised, or revised during a few months, except for
mistakes. In this section I publish condensed news about package
updates, and R-related books and articles published elsewhere.
:::

::: {#recent-posts}
:::

::: {.callout-note collapse=true}
## R Pages

The [R pages](pages.qmd) are informative articles and tutorials that once
published I update as needed to keep them useful and relevant. Many
of the pages are based on material prepared for courses or talks and
republished in a different format. In general, the focus is not on
cookbook-style R code examples.
:::

::: {#recent-pages}
:::

::: {.callout-note collapse=true}
## R Gallery

The [R gallery](galleries.qmd) contains pages that demonstrate use cases
of R and R packages, mostly my own packages. Each page contains multiple
R-code recipes for ploting and computations for specific tasks, cookbook
style. The aim is to provide additional recipes complementing those in
the well known [Cookbook for R](http://www.cookbook-r.com/) website.
Once pages in this section are published they are updated as needed to
keep them useful and relevant, and possibly to expand them.
:::

::: {#recent-galleries}
:::

::: {.callout-note collapse=true}
## SenPEP research blog

These posts are related to research with plants and crops in the research group I lead: _Sensory Ecology and Photobiology of Plants (SenPEP)_.
:::

::: {#recent-senpep}
:::

::: {.callout-tip collapse=true}
# Feeds and announcements

**The best way to remain up-to-date about the contents of this site is to
use an RSS feed reader** such as NetNewsWire (iPhone) or a browser add-on
like "FeedBro" (Firefox) and subscribe to the feeds you are interested
in. The RSS entry in the site's main menu contains links to three
separate feeds, for the _Blog_, _Pages_ and _R Gallery_ sections of the
website.

**I publish occasionally announcements through Mastodon.** I use [hashes to
differentiate posts by subject](posts/Mastodon-updates/index.qmd) so
that you can follow what you are interested in without cluttering your
Mastodon Home. You can see my first post through Mastodon or [my first
*toot*](https://mastodon.social/@aphalo/110389057352585332).

You can visit my Mastodon profile at
[https://mastodon.social/\@aphalo](https://mastodon.social/@aphalo). I
am no longer using Twitter/X or Facebook.
:::

::: {.callout-tip collapse=true}
## Other index pages

These index pages list a selection of posts that are already listed in other index
pages. They are only a convenience.
:::

* [Talks as slides or videos](presentations.qmd)

* [Pages related to R packages 'ggpp' and 'ggpmisc'](ggpp-ggpmisc-index.qmd)

* [Data analysis and statistics with R](r-index.qmd)

::: {.callout-note collapse=true}
# Site navigation and menu

The site is searchable, and the search is based on a static index. In other 
words, the search is fast and local.

# Contents

Opens a nested menue that links to the tables of contents of the different sections.

# R packages

This menu entry gives access to the [documentation in HTML format for all the R
packages that I actively maintain](https://docs.r4photobiology.info).

Under development versions of the packages that I maintain are available at a [CRAN-like repository](https://aphalo.r-universe.dev). I addition to the packages published in CRAN, a few packages are only available through this repository.

# Books

This menu entry gives access to pages related to books I have written or
edited about R and/or photobiology.

# Data

Here you will find data acquired at a weather station that I manage. The 
station is located in the Viikki Campus of the University of Helsinki, 
in Helsinki, Finland. There is also a description of the station equipment
and the variables in the data.

# About

Pages with additional information about the site and myself.

# Feeds

Each index page generates a matching RSS feed that can be followed with any 
compatible feed reader.

:::

