---
title: "IPS-003 (2023)"
subtitle: "Data Analysis and Design of Experiments"
author: Pedro J. Aphalo
author-meta: Pedro J. Aphalo
listing:
  - id: R-intro
    contents:
      - "pages/R-intro.qmd"
      - "pages/ggplot2-introduction.qmd"
      - "pages/r-flow-execution.qmd"
    sort: false
    type: grid
    fields: [title, date-modified, abstract]
  - id: R-advanced
    contents:
      - "galleries/bar-col-plots.qmd"
      - "galleries/quadrant-volcano-plots.qmd"
      - "galleries/plot-equations.qmd"
      - "galleries/pairwise-labels.qmd"
      - "galleries/multcomp.qmd"
      - "galleries/nudge-and-repel.qmd"
      - "galleries/plot-insets.qmd"
      - "galleries/plot-interactive.qmd"
    sort: false
    type: table
    fields: [title, date-modified]
  - id: IPS-003
    contents:
      - "galleries/dataviz-intro.qmd"
      - "pages/ggplot2-EDA.qmd"
      - "pages/approaches-to-research.qmd"
      - "pages/R-model-fitting-intro.qmd"
    sort: false
    type: grid
    fields: [title, date-modified, abstract]
page-layout: full
title-block-banner: true
---

## R and programing

R is a language and an environment for data analysis and visualization. It has
become the standard for data analysis. In Bioinformatics it "competes" with Python, 
but R can "talk" with code written in most other programing languages. Course
IPS-003 focuses on the principles of data analysis and design of experiments. We
use R for exercices and demonstrations. Thus some familiarity with R is needed.
So, I am organizing a short series of meetings to introduce R. These are not part
of IPS-003, and there is no course code for them, but credits will be accrued
and registered under a generic code. The pages below will be used and you will
initially use R online through Posit Cloud (formerly RStudio Cloud).

::: {#R-intro}
:::

Moderately advanced R learning material is available as a free on-line course at
[intro2R](https://alexd106.github.io/intro2R/index.html).

::: {#R-advanced}
:::

The second edition of my book _Learn R: As a Language_ is about to published and
I will provide participants with a copy of the PDF.

## IPS-003

I will be teaching data analysis and design of experiments, which are very 
tightly dependent on each other. Statistics gives theoretical support to data 
analysis methods, but efficiently extracting information from observations from 
experiments and surveys is in many ways like detective work or solving puzzles.
Modern data analysis makes heavy use of visual data displays (plots, diagrams,
garphs). Much of the material for the course is in the pages listed below.

::: {#IPS-003}
:::

Why these pages are not in Moodle? Because I want to make sure they are truly
open access, and that they will remain available after I formally retire next 
year as a Senior Lecturer.
