---
title: "photobiologyWavebands 0.5.1"
author: "Pedro J. Aphalo"
date: 2023-01-05
date-modified: 2023-01-05
categories: [R Package Update]
keywords: [photobiologyWavebands pkg]
---

PAR, or photosynthetically active radiation, as defined by McCree (1972) and used almost universaly in plant sciences is a <em>biological spectral weighting function</em> or <em>BSWF</em> that for spectral irradiance in photon based units takes one of two values for the weights: 0 or 1. So for computations of PAR photon irradiance (or PPFD) it is equivalent to integration over a range of wavelengths without application of a weighting function.

However, PAR, as defined by McCree, has a BSWF with weights that vary with wavelength when used to computed PAR (energy) irradiance, a quantity currently almost never used. Anyway the definition of the `PAR()` waveband constructor in previous versions of the package was conceptually wrong, and has now been fixed. If anybody happened to compute PAR energy irradiance with earlier versions of the package, the results obtained were not weighted. This non-weighted quantity has been in the old literature occasionally also called PAR, but is a "PAR" quantity based on a different defintion than McCree's. In the new version the result from the same computation is weighted, and differs from the one computed using earlier versions to an extent that depends on the shape of the spectrum.

In the update, I not only corrected this bug, but added code implementing several additional ways of computing "PAR-like" quantities, both of historical interest and recently proposed and under debate. I also expanded the documentation explaining the differences among defintions and adding references to the scientific literature.

The names of functions `CIE()` and `ICNIRP()` have a clear meaning only within a very specialized community, as they refer to acronyms fro the names of organizations that have published many different standards related to radiation and its effects. New constructors `erythema()` and `uv_health_hazard()` by default construct identical waveband objects as `CIE()` and `ICNIRP()`, respectively. (The old names remain available.)

The main changes from version [0.5.0]{style="color: #0000ff;"} the previous CRAN release, are:

<ul>

<li class="pm-list-item">

`PAR()` was previously defined as a wavelength range, which is correct only for computations of photon irradiance. For computation of energy irradiance the correct approach is to use a weighting function based on the energy per photon. This now fixed. The previous behaviour of `PAR()` can now be obtained with the new function `PhR()`or by passing an argument to parameter `std`. This change affects only computations of energy irradiance, and although not code breaking, returned values will vary slightly.

</li>

<li class="pm-list-item">

`PAR()` gains definitions of historical interest as well as the recently proposed extended photosynthetically active radiation, ePAR.

</li>

<li class="pm-list-item">

`Plant_bands()` now accepts `"Sellaro"` and `"sensoryBroad"` as argument for `std`.

</li>

<li class="pm-list-item">

`Blue()` and `Green` now accept `"broad"` as argument for `std`, corresponding to very broad ranges of wavelengths as frequently used in plant sciences.

</li>

<li class="pm-list-item">

Update `UVI()` so that it optionally returns integer values as recommended by WWO for communication of UVI to the general public. Default behaviour remains unchanged.

</li>

<li class="pm-list-item">

Add `erythema()` as substitute of `CIE()`, and `UV_health_hazard()` as substitute for `ICNIRP()`. The new functions have a `std` parameter and by default have the same behaviour as the functions they substitute. `CIE()` and `ICNIRP()` are deprecated but maintained to ensure backwards compatibility.

</li>

<li class="pm-list-item">

Updates to documentation.

</li>

</ul>

<strong>Package documentation web site at:</strong><a href="https://docs.r4photobiology.info/photobiologyWavebands/"> https://docs.r4photobiology.info/photobiologyWavebands/</a>

<strong>[NOTE:]{style="color: #0000ff;"} Version 0.5.1 is on its way to [CRAN.]{style="color: #0000ff;"}</strong>

Please raise issues concerning bugs or enhancements to this package through Bitbucket at <a href="https://github.com/aphalo/photobiologyWavebands/issues/">https://github.com/aphalo/photobiologyWavebands/issues/</a>
