---
title: "photobiology 0.10.13"
author: "Pedro J. Aphalo"
date: 2022-10-05
date-modified: 2022-10-05
categories: [R Package Update]
keywords: [photobiology pkg]
---

<hr />

<strong>[BUG FIX:]{style="color: #ff0000; background-color: #ffff99;"}</strong> <em>Sometime during the early life of package 'photobiology' I decided that it was a good idea to support in collections of spectra the use of dimensions as a way of supporting spectral images and similar data. I never managed to buy a spectral camera and make use of this. So the code for dimensions was not much tested or used. As it happens, it contained a bug in the computation of dimensions that triggered odd and not easy to track errors when using negative numerical subscripts or logical subscripts with the extraction operator `[ ]` even with the default one-dimensional collections. I was bitten by this bug some days ago. Hopefully, you as many people usually do, have used only positive numerical values as subscripts and, thus, you have not been bitten by this nasty creature. </em>

<em>This bug is now squashed, and a new version of 'photobiology' ready to move to CRAN. It contains also a few enhancements. </em>

<hr />

Changes from [version 0.10.12]{style="color: #0000ff;"} the most recent CRAN release, are:

<ul>

<li>[Bug fix:]{style="color: #ff0000; background-color: #ffff99;"} The extraction operator `[ ]` for collections of spectra, no longer stores wrong values in the dimension attribute (`"mspct.dim"`) when passed as argument a vector of logical values or a vector of negative numeric values.</li>

<li>Improve handling of missing and default wavebands in `irrad()` and in `trim_waveband()`.</li>

<li>Add preliminary support for filter stacks in `filter.properties` attribute.</li>

<li>Add `summary()` method for collections of spectra.</li>

</ul>

<strong>The package documentation web site at</strong><a href="https://docs.r4photobiology.info/photobiology/"> https://docs.r4photobiology.info/photobiology/</a> includes <a href="https://docs.r4photobiology.info/photobiology/news/index.html">a changelog</a> with information for each release since version 0.1.0.

[<strong>]{style="text-indent: 0em;"}[NOTE:]{style="color: #0000ff;"} Version 0.10.13 is on its way to [CRAN. ]{style="color: #0000ff;"}</strong><strong>[ </strong>]{style="text-indent: 0em;"}

[Please raise issues concerning bugs or enhancements to this package through GitHub at]{style="text-indent: 0em;"}[ <a style="text-indent: 0em; color: #0000ff;" href="https://bitbucket.org/aphalo/photobiology/issues">https://github.com/aphalo/photobiology/issues</a>]{style="color: #0000ff;"}
