---
title: "photobiology 0.10.15"
author: "Pedro J. Aphalo"
date: 2023-01-05
categories: [R Package Update]
keywords: [photobiology pkg]
---

One of the features of the package for a long time has been automatic wavelength interpolation when needed in computations involving two spectra. However, until the current version this behaviour did not extend to operations summarizing multiple spectra stored as members of the same collection, as inconsistent wavelength values triggered an error.

This update to 'photobiology' enhances the compatibility of 'ggspectra' with `spct` objects that have been reduced in size by removal or "thinning" of intermediate wavelength values in rectilinear regions.

Spectra containing data for multiple spectra in long form were not well suported as members of `mspct` collection objects, i.e., some operations available for collections without such members were unsupported.

These changes also enhance the compatibilty of package 'ggspectra' with the presence of inconsistent wavelengths across members of collections of spectra.

Changes from [version 0.10.14]{style="color: #0000ff;"} the most recent CRAN release, are:

<ul>

<li>Add helper function `spct_wide2long()` a simple pure R replacement for `dplyr::pivot_longer()` for spectra.</li>

<li>Revise function `subset2mspct()` to accept collections of spectra and subset (split) members containing multiple spectra in long form.</li>

<li>Revise function `subset2mspct()` to accept any valid `spct` object, inlcuding those containing multiple spectra in long form, and always return a `mspct`.</li>

<li>Add function `is_daytime()` as a wrapper on `day_night()` returning a logical vector.</li>

<li>Make the name and label returned by a call to `waveband()` accepting all defaults arguments, a *not available* `waveband()`, more informative.</li>

<li>Update `e2q()` and `q2e()` to better handle previously normalized spectra passed as arguments: normalization is now refreshed by default.</li>

<li>Increase the accuracy of conversions in `e2q()` and `q2e()`. The change in computed values is at most 20 parts per million.</li>

<li>Add functions for conversions among quantities representable as wave length: `wl2wavenumber()`, `wavenumber2wl()`, `wl2frequency()`, `frequency2wl()`, `wl2energy()` and `energy2wl()`.</li>

</ul>

<strong>The package documentation web site at</strong><a href="https://docs.r4photobiology.info/photobiology/"> https://docs.r4photobiology.info/photobiology/</a> includes <a href="https://docs.r4photobiology.info/photobiology/news/index.html">a changelog</a> with information for each release since version 0.1.0.

[<strong>]{style="text-indent: 0em;"}[NOTE:]{style="color: #0000ff;"} Version 0.10.15 is on its way to [CRAN. ]{style="color: #0000ff;"}</strong><strong>[ </strong>]{style="text-indent: 0em;"}

[Please raise issues concerning bugs or enhancements to this package through GitHub at]{style="text-indent: 0em;"}[ <a style="text-indent: 0em; color: #0000ff;" href="https://bitbucket.org/aphalo/photobiology/issues">https://github.com/aphalo/photobiology/issues</a>]{style="color: #0000ff;"}
