---
title: "ggpmisc 0.5.1"
author: "Pedro J. Aphalo"
date: 2022-10-15
categories: [R Package Update, ggpmisc pkg]
---

Version 0.5.1 brings additional enhancements to the annotations based on model fits. These enhancements improve traceability by updating statistics to return additional information about the fitted models. Functions in 'ggplot2' that had been earlier announced as being at their end-of-life have now been deprecated. Some instances `aes_()` had remained lingering in the code and had to be replaced by `aes()` .

Changes compared to version [0.5.0]{style="color: #0000ff;"}, the previous version in[ CRAN]{style="color: #0000ff;"} are:

<ul>

<li>[Compatibility fix:]{style="background-color: #ccffcc;"} Update for compatibility with upcoming 'ggplot2' 3.4.0 (tested with v3.4.0-rc).</li>

<li>Revise approach used to extract the formula from the fitted model object. Use `formula()` method on fitted model but fall-back onto the 'formula' argument in case of error or return `NA` if everything fails, without triggering an error condition.</li>

<li>Always include variables `fm.tb.type`, `fm.class`, `fm.method`, `fm.formula`, and `fm.formula.chr` in the data returned by `stat_fit_tb()`, and rename `mf_tb` into `fm.tb` for naming consistency.</li>

<li>Always include variable `fm.formula` in the data returned by all other textual-annotation statistics based on model fitting.</li>

<li>Include variables `fm.class`, `fm.method`, and `fm.formula.chr` in addition to `fm.formula` in the data returned by line plotting statistics based on model fitting when passed argument `fm.values = TRUE`.</li>

<li>Add `scale_colour_logFC()`, `scale_color_logFC()` and `scale_fill_logFC()`.</li>

<li>Revise `scale_colour_outcome()` and `scale_fill_outcome()` adding flexibility to the `value` names and allowing a work-around for non-functional `drop` in manual scales due to a bug present in 'ggplot2' (only in versions 3.3.4, 3.3.5, 3.3.6).</li>

<li>Revise <em>User Guide</em>.</li>

</ul>

<em>Documentation web site at <a href="http://docs.r4photobiology.info/ggpmisc/">http://docs.r4photobiology.info/ggpmisc/</a> includes all help pages, with output from all examples, vignettes as well as a changelog in HTML format.</em>

<strong>[NOTE:]{style="color: #0000ff;"}</strong> <strong>Version 0.5.1 is on its way to [CRAN]{style="color: #0000ff;"}. </strong>

Please raise issues concerning bugs or enhancements to this package through GitHub <a href="https://github.com/aphalo/ggpmisc/issues">https://github.com/aphalo/ggpmisc/issues</a>
