---
title: "ggpmisc >= 0.5.0 updates"
subtitle: "ggpmisc: Miscellaneous Extensions to 'ggplot2'"
author: "Pedro J. Aphalo"
date: 2022-08-05
date-modified: 2024-04-07
categories: [R Package Update]
keywords: [ggpmisc pkg]
---

::: callout-note

Since moving the site to Quarto I am updating this post to give a concise
overview of changes. Differences between versions are listed in detail in the
[NEWS file](https://docs.r4photobiology.info/ggmisc/news/).

:::

## Overview of changes

_Version 0.5.6_ fixes bugs and implements enhancements to `stat_multcomp()` and tracks changes in 'ggplot2' >= 3.5.0. **Depends directly on 'ggpp' >= 0.5.7, and indirectly on 'ggplot2' >= 3.5.0.**

_Version 0.5.5_ fixes bug that prevented use of model formulas with a transformation in the _lhs_, such as use of `I()` or other functions instead of bare `y` or `x`.

_Version 0.5.4_ brings `stat_multcomp()` for computing multiple comparisons within the framework of _general linear hypothesis_ as implemented in R package 'multcomp' and annotation of plots with the outcomes.

_Version 0.5.3_ fixes bugs, brings compatibility with package 'gganimate' and adds parameter `n.min` to all statistics that are based on model fitting or correlation testing functions. Arguments passed to `n.min` make it possible to increase the previously hard-coded limit that remains in most cases as the default.

_Version 0.5.2_ fixes bugs and ensures compatibility with updates to 'ggplot2' and 'lubridate'. 

_Version 0.5.1_ brings additional enhancements to the annotations based on model fits to improve traceability. New scales `scale_colour_logFC()`, `scale_color_logFC()` and `scale_fill_logFC()` and revised `scale_colour_outcome()` and `scale_fill_outcome()` add flexibility.

_Version 0.5.0_ brings enhancements to the annotations based on model fits. The most visible change is the new convenience function `use_label()` that greatly simplifies the assembly of labels from components and their mapping to aesthetics. Function `stat_correlation()` now computes confidence intervals for correlation estimates. New functions `keep_tidy()`, `keep_glance()` and `keep_augment()` are wrappers on methods `tidy()`, `glance()` and `augment()` from package 'broom'. These new functions make it possible to keep a trace of the origin of the _"broom-tidied"_ outputs similarly as it is possible with `"lm"` objects and other objects returned by R's model fitting functions.

[*Documentation web site*](http://docs.r4photobiology.info/ggpmisc/) includes all help pages, with output from all examples and vignettes in HTML format .

Please raise issues concerning bugs or enhancements to this package through GitHub at <https://github.com/aphalo/ggpmisc/issues>. Pull requests are also welcome.
