---
title: "ggpp 0.5.0"
author: "Pedro J. Aphalo"
date: 2022-12-05
categories: [R Package Update]
keywords: [ggpp pkg]
---

Version [0.5.0]{style="color: #0000ff;"} includes <strong>code-breaking</strong> enhancements to `geom_text_s()` and `geom_label_s()`. The most significative is a mechanism to selectively applying aesthetics to different components of linked labels and text. This replaces the previous use of separate aesthetics applied only to segments or arrows. The reason behind this change is that segments are only links, and not meant to inform about data values on their own.

Please see the post [Enhancing geom_text() and geom_label()](../Enhancing-geom-text/) for example plots.

Changes compared to version [0.4.5]{style="color: #0000ff;"}, the previous version in [CRAN]{style="color: #0000ff;"} are:

<ul>

<li>Update `geom_label_s()`, `geom_text_s()`, `geom_point_s()`, `geom_plot()`, `geom_table()` and `geom_grob()` adding Add parameters `default.colour` and `colour.target` .</li>

<li>Update `geom_text_s()` and `geom_label_s()` to parameters `default.alpha` and `alpha.target`.</li>

<li>[Code breaking.]{style="color: #ff0000;"} Remove support for aesthetics `segment.colour`, `segment.alpha`, and `segment.size` in `geom_label_s()`, `geom_text_s()`, `geom_point_s()`, `geom_plot()`, `geom_table()` and `geom_grob()`.</li>

<li>Add functions `stat_panel_counts()` and `stat_group_counts()`.</li>

<li>Document in a separate vignette the use of the repulsive geoms from package 'ggrepel' together with postions and statistics from package 'ggpp'.</li>

<li>Add a cheat sheet and improve the README file.</li>

</ul>

<em>Documentation web site at <a href="http://docs.r4photobiology.info/ggpp/">http://docs.r4photobiology.info/ggpp/</a> includes all help pages, with output from all examples, vignettes as well as a changelog in HTML format.</em>

<strong>[NOTE:]{style="color: #0000ff;"}</strong> Version 0.5.0 is on its way to [CRAN]{style="color: #0000ff;"}.<strong> </strong>

Please raise issues concerning bugs or enhancements to this package through GitHub at <a href="https://github.com/aphalo/ggpp/issues">https://github.com/aphalo/ggpp/issues.</a> Pull requests are also welcome.
