---
title: "gginnards 0.1.1"
author: "Pedro J. Aphalo"
date: 2022-10-15
categories: [R Package Update, gginnards pkg]
---

This is a maintenance release, with minor enhancements and edits for compatibility with upcoming 'ggplot2' 3.4.0. The only highly visible change is in more clearly separating the roles of the debug statistics and the debug geom by setting `geom_null()` as the default for the statistics.

Changes compared to 'gginnards' 0.1.0:

::: {.body .pm-cursor-color .pm-text-color .pm-background-color .pm-editing-root-node data-pm-slice="4 2 []"}
::: pm-content
<ul class="pm-list pm-bullet-list">

<li class="pm-list-item">

Update `geom_debug()` to avoid several spurious warnings triggered by unrecognized parameters and aesthetics. Aesthetics silently accepted include all those used by geoms from packages 'ggplot2', 'ggpp', and 'ggrepel'.

</li>

<li class="pm-list-item">

Improve the printed output from `geom_debug()`, `stat_debug_group()` and `stat_debug_panel()`.

</li>

<li class="pm-list-item">

Change the default geom of `stat_debug_group()` and `stat_debug_panel()` from `"debug"` to `"null"`.

</li>

<li class="pm-list-item">

Tested working with 'ggplot2' 3.3.6 and upcoming 'ggplot2' 3.4.0 (v3.4.0-rc).

</li>

</ul>
:::
:::

Documentation web site at <a href="http://docs.r4photobiology.info/gginnards/">http://docs.r4photobiology.info/gginnards/</a> includes all help pages, with output from all examples, and vignettes in HTML format.

<strong>[NOTE:]{style="color: #0000ff;"} The new version of the package is on its way to [CRAN]{style="color: #0000ff;"}. </strong>

Please raise issues concerning bugs or enhancements to this package through GitHub <a href="https://github.com/aphalo/gginnards/issues">https://github.com/aphalo/gginnards/issues</a>
