---
title: "Website migrated to Quarto"
author: "Pedro J. Aphalo"
date: "2023-02-27"
date-modified: "2023-03-29"
categories: [website news]
---

**I have moved this website from WordPress to [Quarto](https://quarto.org/).**
The address <https://www.r4photobiology.info/> remains unchanged.

I have migrated only part of the content from the old site. In particular I have
not migrated old package update announcements as they mostly repeated the
contents of the NEWS files (log file) of the packages, which contain a summary
of their whole development history.

I have converted some posts that I consider of long-term interest into pages. I
have added a new section of galleries of code examples demonstrating the use of,
at the moment, packages 'ggpp' and 'ggpmisc'. The galleries have some new
material together with examples copied or adapted from the packages'
documentation but organized in a way that should make them easier to serve as a
reference or "cookbook" of recipes.

WordPress is a dynamic system implemented using a data base. Pages are built
when served. This is useful when the contents are actually dynamic, but adds
overhead when not needed, making the site slower and requiring computation
that wastes energy. In addition the site when in WordPress required plugins
which add a security risk as well as making more complicated GDR compliance.
A totally static system just serves ready-made pages and does not need to
collect information from users or the client software and/or hardware to work.

The Blog index page is no longer the Home page of the website. I have for
the time being emphasized easy of maintenance and functionality over how the 
site looks. I am still learning the details about Quarto, and the site will
evolve as I make progress. You will see changes, for example in the use of
categories.
