---
title: "photobiology 0.10.14"
author: "Pedro J. Aphalo"
date: 2022-10-15
categories: [R Package Update, photobiology pkg]
---

<hr />

[<strong>COMPATIBILITY FIX:</strong> ]{style="background-color: #ccffcc;"}An update of package 'tidyselect' 1.2.0 now in CRAN deprecated syntax previously accepted. This change affected indirectly the syntax used in 'dplyr' and 'tidyr' resulting in lots of warnings and in a few odd behaviours in 'photobiology'. To solve this I replaced several calls to `dplyr::rename()` and `dplyr::select()` with newly written code using only base R functions and operators.

<hr />

Changes from [version 0.10.13]{style="color: #0000ff;"} the most recent CRAN release, are:

<ul>

<li>[Compatibility fix:]{style="background-color: #ccffcc;"} track changes in syntax brought by package 'tidyselect' 1.2.0 and possibly 'rlang' 1.0.6, affecting 'photobiology' through 'dplyr' and 'tidyr'.</li>

<li>Fix some bugs, including an edge case of handling of spectra with with only `NA` values in `w.length` variable.</li>

<li>Add function `illuminance()`.</li>

</ul>

<strong>The package documentation web site at</strong><a href="https://docs.r4photobiology.info/photobiology/"> https://docs.r4photobiology.info/photobiology/</a> includes <a href="https://docs.r4photobiology.info/photobiology/news/index.html">a changelog</a> with information for each release since version 0.1.0.

[<strong>]{style="text-indent: 0em;"}[NOTE:]{style="color: #0000ff;"} Version 0.10.14 is on its way to [CRAN. ]{style="color: #0000ff;"}</strong><strong>[ </strong>]{style="text-indent: 0em;"}

[Please raise issues concerning bugs or enhancements to this package through GitHub at]{style="text-indent: 0em;"}[ <a style="text-indent: 0em; color: #0000ff;" href="https://bitbucket.org/aphalo/photobiology/issues">https://github.com/aphalo/photobiology/issues</a>]{style="color: #0000ff;"}
