---
title: "ooacquire 0.2.4 and 0.2.5"
author: "Pedro J. Aphalo"
date: 2022-10-01
categories: [R Package Update, ooacquire pkg]
---

The main new feature in version 0.2.5 is that the package can be installed and used in an <strong>off-line mode</strong> without need to install what were previously system requirements and required packages. In this mode data acquisition and communication with spectrometers is disabled, but processing of spectral data previously acquired or acquired with a different computer or using other software remains available unchanged.

Version 0.2.4 brings some improvements to the user interface for interactive data acquisition. It also fixes problems caused by code-breaking changes in package 'readr'.

Main changes in version 0.2.5 compared to version 0.2.4 are:
<ul class="pm-list pm-bullet-list" data-tight="true" data-pm-slice="3 3 [&quot;body&quot;,null]">
 	<li class="pm-list-item">Implement an <strong>off-line</strong> mode in which data acquisition is disabled but computations still possible. The <strong>off-line</strong> mode is automatically entered if package 'rOmniDriver' is not installed or if its initialization fails. This change removes the need to install Java, drivers from Ocean Insight and R packages 'rOmniDriver' and 'rJava' when data to be processed have been acquired using another computer or with software from Ocean Insight.</li>
 	<li><span style="background-color: #ffff99;">Fix bug</span> in the generation of the `.CSV` file with summaries for collections of spectra.</li>
</ul>
Main changes in version 0.2.4 compared to vversion 0.2.3 are:
<ul>
 	<li>Function `acquire_continuous_interactive()` gains three new parameters that make it possible to override defaults and gets several small tweaks to the user interface including dynamic default for protocol.</li>
 	<li>Function `acquire_continuous_interactive()` now sets defaults for user/operator name, session name and folder used for output based on logged-in user's name, current day and time and spectral quantity returned.</li>
 	<li>Revise the user interaction in `set_folder_interactive()` and add check for success of new folder creation.</li>
 	<li>Support in `acq_raw_mspct()` the acquisition of a timed sequence of spectra.</li>
 	<li>Improve summary for collection of spectra in `acq_continuous_interactive()`.</li>
 	<li><span style="background-color: #ffff99;">Fix bug</span> in reading of raw data from files possibly caused by changes in package 'readr'.</li>
 	<li><span style="background-color: #ffff99;">Fix bug</span> in `which_descriptor()` that resulted in wrong text in warnings.</li>
 	<li><span style="background-color: #ffff99;">Fix bug</span> in `which_descriptor()` that resulted in failure to handle gaps between the validity of calibrations or dates before the earliest calibration.</li>
 	<li>Expand description of algorithms.</li>
 	<li>Test with OmniDriver 2.56 and 2.68.</li>
</ul>
Full change history is available at: <a href="https://docs.r4photobiology.info/ooacquire/news/index.html">https://docs.r4photobiology.info/ooacquire/news/index.html</a>

<strong><span style="color: #ff0000;">NOTE:</span> This package is NOT available through CRAN.
</strong>

This package is available through the <span style="color: #0000ff;">r4photobiology repository</span><span style="text-indent: 0em;"> and through GitHub.
</span>

## Installation

Note: this version needs the recently released 'rOmniDriver' version 0.1.14 or later (version 2.56 is known to work), so if this package is already installed it may need to be updated before updating or installing 'ooacquire' &gt;= 0.2.3.
<ol>
 	<li>From the binary or source packages of the <em><strong>released version</strong></em> from the CRAN-compatible repository at <a href="http://r.r4photobiology.info/">http://r.r4photobiology.info/</a>.</li>
 	<li>From sources of the <em><strong>under development version</strong></em> retrieved from the Git repository at GitHub. Version tags indicate the releases.</li>
</ol>

```{r, eval=FALSE}
devtools::install_github("aphalo/romnidriver")
devtools::install_github("aphalo/ooacquire")
```

Please raise issues concerning bugs or enhancements to this package through GitHub at <a href="https://github.com/aphalo/ooacquire/issues" target="_blank" rel="noopener">https://github.com/aphalo/ooacquire/issues</a>
